import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 20,
    padding: 10,
    alignItems: 'center',
    width: '100%',
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    textAlign: 'center',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
  },
  marginContainer: {
    marginTop: 20,
    width: '100%',
  },
  subContainer: {
    marginTop: 10,
    width: '100%',
    alignItems: 'center',
  },
  createTableContainer: {
    alignItems: 'center',
    flex: 1,
    marginTop: 100,
  },
  createTableText: {
    fontSize: 40,
    marginBottom: 50,
  },
  createTableButton: {
    height: 100,
    width: 100,
    marginTop: 20,
    borderRadius: 10,
    borderColor: '#4ff8ff',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  coloredText: {
    color: '#4ff8ff',
    fontSize: 30,
  },
  backgroundStyle: {
    borderWidth: 1,
    flex: 1,
  },
  howManyPeopleText: {
    fontSize: 30,
    textAlign: 'center',
    marginBottom: 20,
  },
  howManyPeopleTextInput: {
    borderWidth: 1,
    padding: 20,
    marginTop: 20,
    width: '25%',
    borderRadius: 10,
    fontSize: 20,
    textAlign: 'center',
  },
  back: {
    alignSelf: 'flex-start',
    marginLeft: 10,
    justifyContent: 'center',
  },
  backText: {
    textAlign: 'left',
  },
  stateContainer: {
    flex: 1,
    alignItems: 'center',
  },
  createButton: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginTop: 20,
  },
  partyContainer: {
    flex: 1,
    marginTop: 20,
    paddingVertical: 10,
    alignItems: 'center',
  },
  itemContainer: {
    backgroundColor: 'white',
    padding: 20,
    marginBottom: 5,
    marginRight: 10,
    borderRadius: 10,
    margin: 10,
    shadowColor: 'black',
    shadowRadius: 10,
    shadowOffset: {width: 10, height: 10},
    shadowOpacity: 0.2,
  },
  listContainer: {
    width: '100%',
    maxHeight: 340,
  },
  listItem: {
    fontSize: 20,
    textAlign: 'center',
  },
  textInput: {
    borderWidth: 1,
    padding: 20,
    width: 200,
    borderRadius: 10,
    fontSize: 20,
    textAlign: 'center',
  },
  smallTextInput: {
    borderWidth: 1,
    padding: 10,
    width: 100,
    borderRadius: 10,
    fontSize: 15,
    textAlign: 'center',
  },
  memberItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: 'black',
    shadowRadius: 5,
    shadowOffset: {width: 10, height: 10},
    shadowOpacity: 0.2,
  },
  addItemText: {
    textAlign: 'center',
  },
  addItemButton: {
    borderWidth: 1,
    borderRadius: 10,
    width: 50,
    height: 50,
    marginTop: 20,
    marginBottom: 10,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  itemText: {
    width: 90,
  },
  resultsContainer: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  results: {
    borderWidth: 1,
    height: '80%',
    width: '90%',
    borderRadius: 10,
    backgroundColor: 'white',
    padding: 10,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
  },
  label: {
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
    marginRight: 10,
  },
  resultsMemberContainer: {
    borderWidth: 1,
    padding: 10,
    marginBottom: 5,
    marginTop: 5,
    borderRadius: 10,
  },
  popupContainer: {
    position: 'absolute',
    borderRadius: 10,
    padding: 10,
    transform: [{translateX: 160}, {translateY: 175}],
    backgroundColor: '#00ff00',
    zIndex: 10,
    justifyContent: 'center',
    shadowColor: 'black',
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.2,
  },
  itemTextContainer: {
    flexDirection: 'row',
  },
});

export default styles;
